// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mailman.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailmanService_SendEmail_FullMethodName      = "/mailman.v1.MailmanService/SendEmail"
	MailmanService_SendEmailBatch_FullMethodName = "/mailman.v1.MailmanService/SendEmailBatch"
	MailmanService_GetEmailStatus_FullMethodName = "/mailman.v1.MailmanService/GetEmailStatus"
	MailmanService_ListTemplates_FullMethodName  = "/mailman.v1.MailmanService/ListTemplates"
)

// MailmanServiceClient is the client API for MailmanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mailman service handles email sending for all internal services.
type MailmanServiceClient interface {
	// SendEmail enqueues a single email for delivery.
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	// SendEmailBatch enqueues multiple emails in a single request.
	SendEmailBatch(ctx context.Context, in *SendEmailBatchRequest, opts ...grpc.CallOption) (*SendEmailBatchResponse, error)
	// GetEmailStatus retrieves the current status of an email job.
	GetEmailStatus(ctx context.Context, in *GetEmailStatusRequest, opts ...grpc.CallOption) (*GetEmailStatusResponse, error)
	// ListTemplates returns all available email templates.
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
}

type mailmanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailmanServiceClient(cc grpc.ClientConnInterface) MailmanServiceClient {
	return &mailmanServiceClient{cc}
}

func (c *mailmanServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, MailmanService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailmanServiceClient) SendEmailBatch(ctx context.Context, in *SendEmailBatchRequest, opts ...grpc.CallOption) (*SendEmailBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailBatchResponse)
	err := c.cc.Invoke(ctx, MailmanService_SendEmailBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailmanServiceClient) GetEmailStatus(ctx context.Context, in *GetEmailStatusRequest, opts ...grpc.CallOption) (*GetEmailStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailStatusResponse)
	err := c.cc.Invoke(ctx, MailmanService_GetEmailStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailmanServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, MailmanService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailmanServiceServer is the server API for MailmanService service.
// All implementations must embed UnimplementedMailmanServiceServer
// for forward compatibility.
//
// Mailman service handles email sending for all internal services.
type MailmanServiceServer interface {
	// SendEmail enqueues a single email for delivery.
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	// SendEmailBatch enqueues multiple emails in a single request.
	SendEmailBatch(context.Context, *SendEmailBatchRequest) (*SendEmailBatchResponse, error)
	// GetEmailStatus retrieves the current status of an email job.
	GetEmailStatus(context.Context, *GetEmailStatusRequest) (*GetEmailStatusResponse, error)
	// ListTemplates returns all available email templates.
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	mustEmbedUnimplementedMailmanServiceServer()
}

// UnimplementedMailmanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailmanServiceServer struct{}

func (UnimplementedMailmanServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedMailmanServiceServer) SendEmailBatch(context.Context, *SendEmailBatchRequest) (*SendEmailBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailBatch not implemented")
}
func (UnimplementedMailmanServiceServer) GetEmailStatus(context.Context, *GetEmailStatusRequest) (*GetEmailStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailStatus not implemented")
}
func (UnimplementedMailmanServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedMailmanServiceServer) mustEmbedUnimplementedMailmanServiceServer() {}
func (UnimplementedMailmanServiceServer) testEmbeddedByValue()                        {}

// UnsafeMailmanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailmanServiceServer will
// result in compilation errors.
type UnsafeMailmanServiceServer interface {
	mustEmbedUnimplementedMailmanServiceServer()
}

func RegisterMailmanServiceServer(s grpc.ServiceRegistrar, srv MailmanServiceServer) {
	// If the following call pancis, it indicates UnimplementedMailmanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailmanService_ServiceDesc, srv)
}

func _MailmanService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailmanServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailmanService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailmanServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailmanService_SendEmailBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailmanServiceServer).SendEmailBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailmanService_SendEmailBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailmanServiceServer).SendEmailBatch(ctx, req.(*SendEmailBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailmanService_GetEmailStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailmanServiceServer).GetEmailStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailmanService_GetEmailStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailmanServiceServer).GetEmailStatus(ctx, req.(*GetEmailStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailmanService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailmanServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailmanService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailmanServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailmanService_ServiceDesc is the grpc.ServiceDesc for MailmanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailmanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailman.v1.MailmanService",
	HandlerType: (*MailmanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _MailmanService_SendEmail_Handler,
		},
		{
			MethodName: "SendEmailBatch",
			Handler:    _MailmanService_SendEmailBatch_Handler,
		},
		{
			MethodName: "GetEmailStatus",
			Handler:    _MailmanService_GetEmailStatus_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _MailmanService_ListTemplates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mailman.proto",
}
