// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type EmailTemplate struct {
	Name              string    `json:"name"`
	Subject           string    `json:"subject"`
	HtmlBody          string    `json:"html_body"`
	TextBody          *string   `json:"text_body"`
	BaseTemplateName  *string   `json:"base_template_name"`
	RequiredVariables []string  `json:"required_variables"`
	Version           int32     `json:"version"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
