// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlc

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO email_templates (name, subject, html_body, text_body, base_template_name, required_variables, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING name, subject, html_body, text_body, base_template_name, required_variables, version, created_at, updated_at
`

type CreateTemplateParams struct {
	Name              string   `json:"name"`
	Subject           string   `json:"subject"`
	HtmlBody          string   `json:"html_body"`
	TextBody          *string  `json:"text_body"`
	BaseTemplateName  *string  `json:"base_template_name"`
	RequiredVariables []string `json:"required_variables"`
	Version           int32    `json:"version"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.BaseTemplateName,
		arg.RequiredVariables,
		arg.Version,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.BaseTemplateName,
		&i.RequiredVariables,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT name, subject, html_body, text_body, base_template_name, required_variables, version, created_at, updated_at
FROM email_templates
WHERE name = $1
`

func (q *Queries) GetTemplate(ctx context.Context, name string) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplate, name)
	var i EmailTemplate
	err := row.Scan(
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.BaseTemplateName,
		&i.RequiredVariables,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT name, subject, html_body, text_body, base_template_name, required_variables, version, created_at, updated_at
FROM email_templates
ORDER BY name, version DESC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailTemplate{}
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.Name,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.BaseTemplateName,
			&i.RequiredVariables,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
